version: "3.9"
services:
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    links:
      - db
volumes:
  db:
    driver: local
  init_db:
    driver: local

